name: seenear
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # ui
  cupertino_icons: ^1.0.2
  animations: ^2.0.7
  fluttertoast: ^8.2.2
  # status manage
  provider: ^6.0.5
  # images
  flutter_svg: ^2.0.7
  #login
  kakao_flutter_sdk: ^1.5.0
  sign_in_with_apple: ^4.3.0
  # routing
  go_router: ^10.0.0
  # device file path
  path_provider: ^2.1.0
  # device permission
  permission_handler: ^10.4.3
  # env file
  flutter_dotenv: ^5.1.0
  # network
  dio: ^5.3.2
  # json
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1
  build_runner: ^2.4.6
  # database
  shared_preferences: ^2.2.0
  # utils
  screenshot: ^2.1.0
  url_launcher: ^6.1.12
  lakos: ^2.0.3

  equatable: ^2.0.5
  intl: ^0.18.1
  collection: ^1.17.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/svg/
    - .env

  fonts:
    - family: pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Regular.otf
        - asset: assets/fonts/Pretendard-Thin.otf
          weight: 100
        - asset: assets/fonts/Pretendard-ExtraLight.otf
          weight: 200
        - asset: assets/fonts/Pretendard-Light.otf
          weight: 300
        - asset: assets/fonts/Pretendard-Regular.otf
          weight: 400
        - asset: assets/fonts/Pretendard-Medium.otf
          weight: 500
        - asset: assets/fonts/Pretendard-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Pretendard-Bold.otf
          weight: 700
        - asset: assets/fonts/Pretendard-ExtraBold.otf
          weight: 800
        - asset: assets/fonts/Pretendard-Black.otf
          weight: 900
    - family: grandmother
      fonts:
        - asset: assets/fonts/Together-Kimyusik.otf
